---
image: docker:19.03.5
services:
  - docker:19.03.5-dind

variables:
  BRANCH: $CI_COMMIT_REF_NAME
  CONTAINER_NAME: anno-$CI_PIPELINE_ID
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test

.image-setup:
  before_script:
    - apk add --update make git

run_pytest:
  extends: .image-setup
  stage: test
  before_script:
    - apk add --update make git
  script:
    - make download-data
    - make test
  after_script:
    - make cleanup

build:
  stage: build
    extends: .image-setup
  script:
    - make build-annobuilder
    - make build
