---
# ref: https://docs.gitlab.com/ee/ci/yaml/index.html#workflowrules-templates
# tag pipeline > MR pipeline > dev pipeline
workflow:
    rules:
        - if: $CI_COMMIT_TAG
        - if: $CI_MERGE_REQUEST_IID
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: docker:20.10.7
services:
    - docker:20.10.7-dind

variables:
    BRANCH: $CI_COMMIT_REF_NAME
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    # CERTDIR used by dind
    DOCKER_TLS_CERTDIR: /certs
    # CERT_PATH and TLS_VERIFY needed by docker client in release_singularity
    DOCKER_CERT_PATH: /certs/client
    DOCKER_TLS_VERIFY: 1
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2376
    # show useful build info
    BUILDKIT_PROGRESS: plain

    # we can only build to one image name, everything has to be done under tags
    PIPELINE_ID: anno-$CI_PIPELINE_ID
    USE_REGISTRY: 1

    # singularity-in-docker
    SID_IMAGE: quay.io/singularity/singularity
    SID_VERSION: v3.8.1
    SID_SLUG: $SID_IMAGE:$SID_VERSION

    # ignore any breakpoint()s that might have made it into a commit
    PYTHONBREAKPOINT: 0

stages:
    - build
    - test
    - release

.base_setup: &image-setup
    before_script:
        - apk add --no-cache --update make git bash jq
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.test_setup: &test-setup
    extends: .base_setup
    stage: test
    # manual trigger if commit starts with skip-test, otherwise always
    rules:
        - if: '$CI_COMMIT_TITLE =~ /^skip-test\b/'
          when: manual
          allow_failure: true
        - when: always
    needs: ['build_docker']

# build both at once to reuse local cache
build_docker:
    stage: build
    extends: .base_setup
    script:
        - make ci-build-docker
        - make ci-push-docker
    tags:
        - bastion

check_do:
    extends: .test_setup
    script:
        - make pull-builder verify-digital-ocean
    tags:
        - bastion

check_pipenv:
    extends: .test_setup
    script:
        - make pull-builder pipenv-check
    tags:
        - bastion
    allow_failure: true

shellcheck:
    extends: .test_setup
    script:
        - make ci-build-devcontainer test-lint
    tags:
        - do-small

run_pytest:
    extends: .test_setup
    script:
        - make pull
        - make download-data RUN_CMD_ARGS="--skip-validation --force"
        - make test
        - make test-ops
    tags:
        - do-small
    rules:
        # manual trigger if commit starts with skip-test, otherwise always
        - if: '$CI_COMMIT_TITLE =~ /^skip-test\b/'
          when: manual
          allow_failure: true
        - when: always

release_singularity:
    stage: release
    image:
        name: $SID_SLUG
        entrypoint: ['']
    variables:
        RELEASE_TAG: $CI_COMMIT_REF_NAME
    before_script:
        - make ci-release-init
    script:
        - make ci-release
    artifacts:
        paths:
            - '*.sif'
        expire_in: 30 days
    rules:
        # automatically generate release artifacts for tags and dev
        - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
        # allow manual triggering on merge requests to avoid creating fake tags when testing changes
        # to release process/artifacts. Will block waiting for manual trigger without allow_failure
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: manual
          allow_failure: true
    tags:
        - bastion
