---
variables:
  BRANCH: $CI_COMMIT_REF_NAME
  CONTAINER_NAME: anno-$CI_PIPELINE_ID

services:
  - docker:19.03.5-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test

run_pytest:
  stage: test
  script:
    - make download-data
    - make test
  after_script:
    - make cleanup

build:
  stage: build
  before_script:
    - apk add --update make
  script:
    - make build-annobuilder
    - make build
