#!/bin/bash -e

source /anno/ops/pg_sourceme

# This creates the postgres data directory ($PGDATA) and initial db files, starts the server, and then loads
# the UTA data from the tarball.
#
# After that is complete, we make sure to shutdown postgres gently. Some shutdown modes will put postgres in bad
# state, causing restarts to take a long time (replay of xlog/transaction logs)

echo "Init of Postgres cluster in ${PGDATA}"
mkdir -p "${PGDATA}"
chown postgres "${PGDATA}"

echo "Creating database cluster in ${PGDATA}"
gosu postgres ${PG_BIN}/initdb

# use custom postgres conf
cp /anno/ops/postgresql.conf "${PGDATA}"/
chown postgres "${PGDATA}"/postgresql.conf

# Start postgres
pg_start &
# shellcheck disable=2119
pg_wait_for_ready # make sure postgres has started before loading data

echo "Setting up database from uta_${UTA_VERSION}.pgd.gz"
# remove old users, if existing
dropdb -h localhost -U postgres --if-exists uta
dropuser -h localhost -U postgres --if-exists uta_admin
dropuser -h localhost -U postgres --if-exists anonymous

# create new users  and load data
createuser -h localhost -U postgres anonymous
createuser -h localhost -U postgres uta_admin
createdb -h localhost -U postgres -O uta_admin uta
gzip -cdq "uta_${UTA_VERSION}.pgd.gz" | grep -v "^REFRESH MATERIALIZED VIEW" | psql -h localhost -U uta_admin --q --echo-errors --single-transaction -v ON_ERROR_STOP=1 -d uta

echo "Refreshing materialized views"
psql -h localhost -U uta_admin -d uta -c "REFRESH MATERIALIZED VIEW uta_${UTA_VERSION}.exon_set_exons_fp_mv;"
psql -h localhost -U uta_admin -d uta -c "REFRESH MATERIALIZED VIEW uta_${UTA_VERSION}.tx_exon_set_summary_mv;"
psql -h localhost -U uta_admin -d uta -c "REFRESH MATERIALIZED VIEW uta_${UTA_VERSION}.tx_def_summary_mv;"

psql -h localhost -U uta_admin -d uta -c "VACUUM (FULL)"

# wait for all the actions to finish and postgres to return to a good state and shut it down cleanly
# shellcheck disable=2119
pg_wait_for_ready
pg_shutdown
touch "${PGDATA}/pgready"
echo "Database ready"
