#!/bin/bash

ts() {
    date +%Y-%m-%d\ %H:%M:%S
}

if [[ "$(id -u -n)" == "root" ]]; then
    pg_user=postgres
else
    pg_user=$(id -u)
fi

export PGDATA=${PGDATA:-"/pg_uta/${pg_user}"}
export PGPORT=${PGPORT:-5432}

export PG_BIN=/usr/lib/postgresql/13/bin
function pg_wait_for_ready() {
    timer=${1:-5}
    retries=${2:-10}
    N=0
    while ! ${PG_BIN}/pg_isready --dbname=postgres --username=postgres --host localhost; do
        echo "[$(ts)] Postgres is unavailable - sleeping for ${timer} seconds"
        N=$((N + 1))
        if ((N > retries)); then
            echo "[$(ts)] Postgres is unavailable - Reached maximum number of retries. Aborting." >&2
            exit 1
        fi
        sleep "${timer}"
    done
}

function pg_shutdown() {
    echo "Shutting down PostgreSQL"
    # if pkill fails (no process found, etc), still exit the script
    if [[ "$(id -u -n)" == "root" ]]; then
        gosu postgres "${PG_BIN}/pg_ctl" stop -m s || exit $?
    else
        "${PG_BIN}/pg_ctl" stop -m s || exit $?
    fi
}

function pg_uta_sync_data() {
    echo "Syncing Postgres UTA data from ${ANNO_DATA}/uta/ to ${PGDATA}"
    mkdir -p "${PGDATA}"
    rsync -a --delete "${ANNO_DATA}/uta/" "${PGDATA}" --info=progress2 2>&1

    # Empty folders are not part of the DigitalOcean data, but postgres expects them. Therefore, create them here.
    pushd "${PGDATA}" || exit $?
    PG_FOLDERS=(
        base/pgsql_tmp
        pg_commit_ts
        pg_dynshmem
        pg_logical/{mappings,snapshots}
        pg_notify
        pg_replslot
        pg_serial
        pg_snapshots
        pg_stat_tmp
        pg_tblspc
        pg_twophase
        pg_wal/archive_status
    )
    mkdir -p "${PG_FOLDERS[@]}"
    chown -R "${pg_user}" "${PGDATA}"
    chmod 0700 "${PGDATA}"
    popd || exit $?
}

function pg_start() {
    echo "Starting PostgreSQL"
    # Enforce a clean shutdown of postgres when process exits
    trap pg_shutdown EXIT
    # if not running in singularity container, use gosu for postgres user
    if [[ "$(id -u -n)" == "root" ]]; then
        exec gosu "${pg_user}" "${PG_BIN}/postgres" -c autovacuum=off
    else
        exec "${PG_BIN}/postgres" -c autovacuum=off
    fi
}
